# Generated by Django 5.0.6 on 2024-06-26 11:13

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='users/person.png', null=True, upload_to='users'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(help_text='Phone must be in this format: 923xxxxxxxxx', max_length=12, unique=True),
        ),
    ]
