# Generated by Django 5.0.6 on 2024-07-16 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_first_name', message='First name must contain only letters', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_last_name', message='Last name must contain only letters', regex='^[a-zA-Z]+$')]),
        ),
    ]
