# Generated by Django 5.0.6 on 2024-07-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('seller', 'Seller')], default='customer', max_length=10),
        ),
    ]
