# Generated by Django 5.0.6 on 2024-06-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='default-slug', max_length=256, unique=True),
        ),
    ]
