# Generated by Django 5.0.6 on 2024-07-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(default='users/person.png', upload_to='product_images'),
        ),
    ]
